config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :users

  root 'recipes#home'

  get 'session/create'
  get 'session/destroy'
  get 'session/new'

  get 'register' => 'users#new'
  get 'users' => 'users#index'
  get 'edit' => 'users#edit'

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy'

  get 'my-recipes' => 'recipes#index'
  get 'new-recipe' => 'recipes#new'

end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  belongs_to :user

  field :name, type: String
  field :url, type: String
  field :category, type: String

  validates_presence_of :name, :url, :category
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_many :recipes

  field :username, type: String
  field :password_digest, type: String

  has_secure_password
  validates_presence_of :username, :password
  validates :username, :uniqueness => true
  validates :password, :length => {
    :minimum => 6,
    :maximum => 20,
    :too_short => "Passwords must be at least %{count} characters.",
    :too_long => "Passwords must be at most %{count} characters."
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :require_user
  protect_from_forgery with: :exception

  def current_user
    if @current_user.nil?
      @current_user = User.find(session[:user_id]) if session[:user_id]
    end
  end
  helper_method :current_user
  
  def require_user
    if current_user
      return true
    end
    redirect_to login_url
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def home
    render :home
  end

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = @current_user.recipes
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @current_user.recipes << @recipe

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :url, :category)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :require_user, :only => [:create, :new]

  def create
    user = User.find_by(username: params[:session][:username])
    if user and user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash[:error] = "Login failed."
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_user, :only => [:create, :new]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render root_path, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-default">
<div class="navbar-class">
  <div class="container">
    <ul class="nav navbar-nav">
        <li><a href="/">cookbook</a></li>
        <% if @current_user %>
            <li><a href="<%= my_recipes_path %>">My Recipes</a></li>
            <li><a href="<%= new_recipe_path %>">New Recipe</a></li>
        <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
            <li><a href="/logout">Logout</a></li>
        <% else %>
            <li><a href="/login">Login</a></li>
            <li><a href="/register">Register</a></li>
        <% end %>
    </ul>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/navbar" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<div class="text-center">
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :name %><br>
        <%= f.text_field :name, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :url, "URL" %><br>
        <%= f.text_field :url, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :category %><br>
       <%= f.select :category, [['Drinks','Drinks'],['Appetizers','Appetizers'],['Entrees','Entrees'],['Desserts','Desserts'],['Snacks','Snacks']], {}, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="actions">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/recipes/edit.html.erb
<div class="text-center">
<h1>Editing Recipe</h1>

<%= render 'form' %>
</div>

app/views/recipes/home.html.erb
<div class="home-wrapper">
    <img src="<%= image_url('hero.jpg') %>">
    <div class="home-wrapper-text">
      <h1>cookbook</h1>
    </div>
</div>

app/views/recipes/index.html.erb
<div class="text-center">

<p id="notice"><%= notice %></p>

<h1>My Recipes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th style="text-align: center;">Name</th>
      <th style="text-align: center;">Category</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><a href="<%= recipe.url %>"><%= recipe.name %></a></td>
        <td><%= recipe.category %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recipes/new.html.erb
<div class="text-center">
  <h1>New Recipe</h1>

  <%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @recipe.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @recipe.category %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<div class='text-center'>

<h1>Log In</h1>

<%= form_for :session, :url => login_path, :method => :post do |f| %>

<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <%= f.label :username %><br>
      <%= f.text_field :username, {class: "form-control"} %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <%= f.label :password, "Password" %><br>
      <%= f.password_field :password, {class: "form-control"} %>
    </div>
  </div><br>
  <div class="actions">
    <%= f.submit "Log In", :class => "btn btn-primary" %>
  </div>
</div>

<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :username, "Username" %><br>
        <%= f.text_field :username, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :password, "Password" %><br>
        <%= f.password_field :password, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="actions">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='text-center'>
  <h1>Editing User</h1>

  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class='text-center'>
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='text-center'>
  <h1>New User</h1>

  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class='text-center'>
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>